version: '3.8'

services:
  server:
    image: vietbac2002/full-stack-demo-server:latest
    ports:
      - 8080:8080
    restart: always
  client:
    image: vietbac2002/full-stack-demo-client:latest
    ports:
      - 80:80
    depends_on:
      - server
    restart: always

