
server:
  port: 8085
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        generate_statistics: true
        hbm2ddl:
          auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true