name: CI/CD Pipeline
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout VCS
      - uses: actions/checkout@v2
      - name: Login with DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build server image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/full-stack-demo:latest -f server/Dockerfile .
      - name: Build client image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/full-stack-demo-client:latest -f client/Dockerfile .
      - name: Push images
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/full-stack-demo:latest && docker push ${{ secrets.DOCKERHUB_USERNAME }}/full-stack-demo-client:latest
  deploy:
    runs-on: [aws-ec2]
    steps:
      - name: Pull images from DockerHub
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/full-stack-demo:latest && docker pull ${{ secrets.DOCKERHUB_USERNAME }}/full-stack-demo-client:latest
      - name: Delete old containers
        run: docker rm -f $(docker ps -a -q)
      - name: Run container with docker-compose
        run: docker-compose up -d
        
      