name: CI/CD Pipeline

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout VCS
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to DockerHub
      - name: Login with DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push the Docker image
      - name: Build and push Docker image server
        uses: docker/build-push-action@v6
        with:
          context: ./server
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/full-stack-demo-server:latest
      
      - name: Build and push Docker image client
        uses: docker/build-push-action@v6
        with:
          context: ./client
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/full-stack-demo-client:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Pulling server image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/full-stack-demo-server:latest
      - name: Pulling client image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/full-stack-demo-client:latest
      - name: Delete old containers
        run: docker rm -f $(docker ps -a -q)
      - name: Docker compose server
        run: docker-compose up -d
        
      
        
        
      

      